spring:
  profiles:
    active: local

  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: update # prod: validate, dev: create, update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      open-in-view: false
      hibernate.query.plan_cache_max_size: 1

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  logging:
    level:
      root: INFO
      com.DoIt2: DEBUG