jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION}

cloud:
  aws:
    s3:
      endpoint: ${R2_ENDPOINT}
      region: auto
      bucket: ${R2_BUCKET}
      access-key: ${R2_ACCESS_KEY}
      secret-key: ${R2_SECRET_KEY}